name: assetx
description: "A simple asset mapping package with shell integration"
version: 0.0.1
homepage: https://github.com/ZackaryW/assetx

executables: 
  assetx: 

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  json_serializable: ">=6.8.0 <7.0.0"
  build_runner: ^2.4.12