name: assetx
description: "A new Flutter package project."
version: 0.2.0
homepage: https://github.com/ZackaryW/assetx

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2
  path: ^1.8.0
  crypto: ^3.0.3
  args: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  assetx:
